#!/usr/bin/env python3
"""
Bubot - Intelligent automation bot for Iceberg snapshot manager
Provides scheduling, monitoring, alerts, and interactive commands
"""

import asyncio
import threading
import time
import json
import re
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Callable, Any
from dataclasses import dataclass, asdict
from iceberg_manager import IcebergManager


@dataclass
class BubotConfig:
    """Configuration for Bubot automation"""
    auto_snapshot_interval: int = 3600  # seconds
    max_snapshots: int = 50
    enable_monitoring: bool = True
    enable_scheduling: bool = True
    enable_alerts: bool = True
    alert_threshold_changes: int = 5
    cleanup_interval: int = 86400  # 24 hours
    storage_path: str = "iceberg_snapshots"


@dataclass
class BubotAlert:
    """Alert generated by Bubot"""
    alert_id: str
    timestamp: float
    alert_type: str
    message: str
    severity: str  # info, warning, error, critical
    metadata: Dict[str, Any]


class BubotScheduler:
    """Handles scheduled tasks for Bubot"""
    
    def __init__(self, manager: IcebergManager, config: BubotConfig):
        self.manager = manager
        self.config = config
        self.running = False
        self.thread = None
        self.last_snapshot_time = time.time()
        self.last_cleanup_time = time.time()
        
    def start(self):
        """Start the scheduler"""
        if self.running:
            return
            
        self.running = True
        
        if self.config.enable_scheduling:
            self.thread = threading.Thread(target=self._run_scheduler, daemon=True)
            self.thread.start()
        
    def stop(self):
        """Stop the scheduler"""
        self.running = False
        if self.thread:
            self.thread.join()
            
    def _run_scheduler(self):
        """Run the scheduler loop"""
        while self.running:
            current_time = time.time()
            
            # Check for auto-snapshot
            if current_time - self.last_snapshot_time >= self.config.auto_snapshot_interval:
                self._auto_snapshot()
                self.last_snapshot_time = current_time
                
            # Check for cleanup
            if current_time - self.last_cleanup_time >= self.config.cleanup_interval:
                self._auto_cleanup()
                self.last_cleanup_time = current_time
                
            time.sleep(10)  # Check every 10 seconds
            
    def _auto_snapshot(self):
        """Create automatic snapshot"""
        try:
            snapshot_id = self.manager.create_snapshot(
                f"Auto-snapshot by Bubot at {datetime.now().isoformat()}",
                metadata={"created_by": "bubot", "auto_generated": True}
            )
            print(f"🤖 Bubot: Created auto-snapshot {snapshot_id}")
        except Exception as e:
            print(f"🤖 Bubot: Error creating auto-snapshot: {e}")
            
    def _auto_cleanup(self):
        """Perform automatic cleanup"""
        try:
            deleted = self.manager.cleanup_old_snapshots(
                keep_count=self.config.max_snapshots
            )
            if deleted > 0:
                print(f"🤖 Bubot: Cleaned up {deleted} old snapshots")
        except Exception as e:
            print(f"🤖 Bubot: Error during cleanup: {e}")


class BubotMonitor:
    """Monitors changes and generates alerts"""
    
    def __init__(self, manager: IcebergManager, config: BubotConfig):
        self.manager = manager
        self.config = config
        self.alerts: List[BubotAlert] = []
        self.last_state = None
        self.change_count = 0
        
    def check_changes(self) -> List[BubotAlert]:
        """Check for changes and generate alerts"""
        if not self.config.enable_monitoring:
            return []
            
        current_state = self.manager.get_current_data_state()
        new_alerts = []
        
        if self.last_state is not None:
            if current_state != self.last_state:
                self.change_count += 1
                
                # Generate alert if too many changes
                if self.change_count >= self.config.alert_threshold_changes:
                    alert = BubotAlert(
                        alert_id=f"alert_{int(time.time())}",
                        timestamp=time.time(),
                        alert_type="high_change_frequency",
                        message=f"Detected {self.change_count} rapid changes in data state",
                        severity="warning",
                        metadata={"change_count": self.change_count}
                    )
                    new_alerts.append(alert)
                    self.change_count = 0
                    
        self.last_state = current_state.copy()
        
        # Add to alerts list
        self.alerts.extend(new_alerts)
        
        # Keep only recent alerts (last 100)
        if len(self.alerts) > 100:
            self.alerts = self.alerts[-100:]
            
        return new_alerts
        
    def get_recent_alerts(self, hours: int = 24) -> List[BubotAlert]:
        """Get alerts from the last N hours"""
        cutoff = time.time() - (hours * 3600)
        return [alert for alert in self.alerts if alert.timestamp >= cutoff]


class BubotCommandProcessor:
    """Processes natural language commands for Bubot"""
    
    def __init__(self, manager: IcebergManager, config: BubotConfig):
        self.manager = manager
        self.config = config
        self.command_patterns = {
            r'create\s+snapshot\s*(.*)': self._cmd_create_snapshot,
            r'show\s+history\s*(\d+)?': self._cmd_show_history,
            r'rollback\s+to\s+(\w+)': self._cmd_rollback_to,
            r'rollback\s+previous': self._cmd_rollback_previous,
            r'compare\s+(\w+)\s+(\w+)': self._cmd_compare,
            r'show\s+current': self._cmd_show_current,
            r'cleanup\s*(\d+)?': self._cmd_cleanup,
            r'status': self._cmd_status,
            r'help': self._cmd_help,
            r'stats': self._cmd_stats,
        }
        
    def process_command(self, command: str) -> str:
        """Process a natural language command"""
        command = command.strip().lower()
        
        for pattern, handler in self.command_patterns.items():
            match = re.match(pattern, command)
            if match:
                try:
                    return handler(match)
                except Exception as e:
                    return f"❌ Error executing command: {e}"
                    
        return f"❓ Unknown command: '{command}'. Type 'help' for available commands."
        
    def _cmd_create_snapshot(self, match) -> str:
        description = match.group(1).strip() or "Snapshot created via Bubot"
        snapshot_id = self.manager.create_snapshot(
            description, 
            metadata={"created_by": "bubot_command"}
        )
        return f"✅ Created snapshot {snapshot_id}: {description}"
        
    def _cmd_show_history(self, match) -> str:
        limit = int(match.group(1)) if match.group(1) else 10
        history = self.manager.get_snapshot_history(limit=limit)
        
        if not history:
            return "📋 No snapshots found"
            
        result = f"📋 Last {len(history)} snapshots:\n"
        for i, snap in enumerate(history, 1):
            result += f"{i}. {snap['snapshot_id'][:8]}... - {snap['description']} ({snap['datetime']})\n"
        return result.strip()
        
    def _cmd_rollback_to(self, match) -> str:
        snapshot_id = match.group(1)
        # Find snapshot by partial ID
        for snap_id in self.manager.snapshots.keys():
            if snap_id.startswith(snapshot_id):
                self.manager.rollback_to_snapshot(snap_id)
                return f"↩️ Rolled back to snapshot {snap_id}"
        return f"❌ Snapshot not found: {snapshot_id}"
        
    def _cmd_rollback_previous(self, match) -> str:
        self.manager.rollback_to_previous()
        current_id = self.manager.get_current_snapshot_id()
        return f"↩️ Rolled back to previous snapshot {current_id}"
        
    def _cmd_compare(self, match) -> str:
        id1, id2 = match.groups()
        
        # Find snapshots by partial IDs
        full_id1 = self._find_snapshot_by_partial_id(id1)
        full_id2 = self._find_snapshot_by_partial_id(id2)
        
        if not full_id1 or not full_id2:
            return f"❌ Could not find snapshots for: {id1}, {id2}"
            
        comparison = self.manager.compare_snapshots(full_id1, full_id2)
        
        result = f"🔍 Comparison between {full_id1[:8]}... and {full_id2[:8]}...\n"
        result += f"Added: {len(comparison['added'])} items\n"
        result += f"Removed: {len(comparison['removed'])} items\n" 
        result += f"Modified: {len(comparison['modified'])} items"
        
        return result
        
    def _cmd_show_current(self, match) -> str:
        current_state = self.manager.get_current_data_state()
        current_id = self.manager.get_current_snapshot_id()
        
        result = f"📊 Current snapshot: {current_id}\n"
        result += f"Data state: {json.dumps(current_state, indent=2)}"
        return result
        
    def _cmd_cleanup(self, match) -> str:
        keep_count = int(match.group(1)) if match.group(1) else 10
        deleted = self.manager.cleanup_old_snapshots(keep_count=keep_count)
        return f"🧹 Cleaned up {deleted} old snapshots, kept {keep_count} most recent"
        
    def _cmd_status(self, match) -> str:
        total_snapshots = len(self.manager.snapshots)
        current_id = self.manager.get_current_snapshot_id()
        current_state_size = len(self.manager.get_current_data_state())
        
        result = f"🤖 Bubot Status:\n"
        result += f"Total snapshots: {total_snapshots}\n"
        result += f"Current snapshot: {current_id[:8] if current_id else 'None'}...\n"
        result += f"Data keys: {current_state_size}\n"
        result += f"Auto-snapshots: {'Enabled' if self.config.enable_scheduling else 'Disabled'}\n"
        result += f"Monitoring: {'Enabled' if self.config.enable_monitoring else 'Disabled'}"
        
        return result
        
    def _cmd_stats(self, match) -> str:
        history = self.manager.get_snapshot_history()
        if not history:
            return "📊 No snapshots to analyze"
            
        # Calculate stats
        total = len(history)
        auto_generated = sum(1 for h in history if h.get('metadata', {}).get('auto_generated'))
        manual = total - auto_generated
        
        # Time since last snapshot
        last_time = datetime.fromisoformat(history[0]['datetime']) if history else None
        time_since_last = datetime.now() - last_time if last_time else None
        
        result = f"📊 Snapshot Statistics:\n"
        result += f"Total snapshots: {total}\n"
        result += f"Auto-generated: {auto_generated}\n"
        result += f"Manual: {manual}\n"
        if time_since_last:
            result += f"Time since last: {str(time_since_last).split('.')[0]}"
            
        return result
        
    def _cmd_help(self, match) -> str:
        return """🤖 Bubot Commands:
        
• create snapshot [description] - Create a new snapshot
• show history [limit] - Show snapshot history
• rollback to <id> - Rollback to specific snapshot
• rollback previous - Rollback to previous snapshot  
• compare <id1> <id2> - Compare two snapshots
• show current - Show current data state
• cleanup [keep_count] - Clean up old snapshots
• status - Show Bubot status
• stats - Show snapshot statistics
• help - Show this help message

Tips:
- You can use partial snapshot IDs (first 4+ characters)
- Commands are case-insensitive
- Use 'status' to check if automation is running"""

    def _find_snapshot_by_partial_id(self, partial_id: str) -> Optional[str]:
        """Find a snapshot by partial ID"""
        for snap_id in self.manager.snapshots.keys():
            if snap_id.startswith(partial_id):
                return snap_id
        return None


class Bubot:
    """Main Bubot class - intelligent automation for Iceberg snapshots"""
    
    def __init__(self, config: Optional[BubotConfig] = None, storage_path: Optional[str] = None):
        self.config = config or BubotConfig()
        if storage_path:
            self.config.storage_path = storage_path
            
        self.manager = IcebergManager(self.config.storage_path)
        self.scheduler = BubotScheduler(self.manager, self.config)
        self.monitor = BubotMonitor(self.manager, self.config)
        self.command_processor = BubotCommandProcessor(self.manager, self.config)
        self.running = False
        
    def start(self):
        """Start Bubot automation"""
        if self.running:
            return
            
        print("🤖 Bubot starting up...")
        self.running = True
        self.scheduler.start()
        
        # Initial monitoring check
        if self.config.enable_monitoring:
            self.monitor.check_changes()
            
        print("🤖 Bubot is now running!")
        print("💡 Type 'help' for available commands")
        
    def stop(self):
        """Stop Bubot automation"""
        if not self.running:
            return
            
        print("🤖 Bubot shutting down...")
        self.running = False
        self.scheduler.stop()
        print("🤖 Bubot stopped")
        
    def command(self, cmd: str) -> str:
        """Process a command and return response"""
        return self.command_processor.process_command(cmd)
        
    def check_alerts(self) -> List[BubotAlert]:
        """Check for new alerts"""
        if not self.config.enable_monitoring:
            return []
        return self.monitor.check_changes()
        
    def get_status(self) -> Dict[str, Any]:
        """Get Bubot status"""
        return {
            "running": self.running,
            "config": asdict(self.config),
            "total_snapshots": len(self.manager.snapshots),
            "current_snapshot": self.manager.get_current_snapshot_id(),
            "recent_alerts": len(self.monitor.get_recent_alerts()),
        }
        
    def interactive_mode(self):
        """Run Bubot in interactive mode"""
        self.start()
        
        try:
            while True:
                try:
                    user_input = input("\n🤖 Bubot> ").strip()
                    
                    if user_input.lower() in ['exit', 'quit', 'bye']:
                        print("👋 Goodbye!")
                        break
                        
                    if user_input:
                        response = self.command(user_input)
                        print(response)
                        
                        # Check for new alerts
                        alerts = self.check_alerts()
                        for alert in alerts:
                            print(f"🚨 Alert: {alert.message}")
                            
                except KeyboardInterrupt:
                    print("\n👋 Goodbye!")
                    break
                except Exception as e:
                    print(f"❌ Error: {e}")
                    
        finally:
            self.stop()


def main():
    """Main entry point for Bubot"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Bubot - Intelligent Iceberg Snapshot Automation")
    parser.add_argument("--storage", default="iceberg_snapshots", help="Snapshot storage path")
    parser.add_argument("--interval", type=int, default=3600, help="Auto-snapshot interval (seconds)")
    parser.add_argument("--max-snapshots", type=int, default=50, help="Maximum snapshots to keep")
    parser.add_argument("--no-scheduling", action="store_true", help="Disable automatic scheduling")
    parser.add_argument("--no-monitoring", action="store_true", help="Disable monitoring")
    parser.add_argument("--command", help="Execute a single command and exit")
    
    args = parser.parse_args()
    
    # Create config
    config = BubotConfig(
        storage_path=args.storage,
        auto_snapshot_interval=args.interval,
        max_snapshots=args.max_snapshots,
        enable_scheduling=not args.no_scheduling,
        enable_monitoring=not args.no_monitoring
    )
    
    # Create Bubot instance
    bubot = Bubot(config)
    
    if args.command:
        # Single command mode
        response = bubot.command(args.command)
        print(response)
    else:
        # Interactive mode
        bubot.interactive_mode()


if __name__ == "__main__":
    main()